server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/localcredit
    # url: jdbc:postgresql://host.docker.internal:5433/localcredit
    username: postgres
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true


